server:
  port: 6000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/masonnpe/config-repository.git
          username: masonnpe
          password: cx245852
          basedir: E:/project/config-repository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true